<?php

namespace CodeLovers\ExamSignupBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExamDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamDateRepository extends EntityRepository
{
}
